<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnSave</name>
   <tag></tag>
   <elementGuidId>81c145fb-ab3f-413e-bcb4-a0fe50b6374b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LinkBtnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LinkBtnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aee878d4-5b9f-409c-8cb4-3fb33b00bbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkBtnSave</value>
      <webElementGuid>968ee11c-92fe-4f93-ae28-3a053df668f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>b4f03701-83b4-4059-a240-97502d555123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>875a5a08-6d8d-410d-af54-98f033d7f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('LinkBtnSave','')</value>
      <webElementGuid>8466670a-5ce7-4dbd-bae1-715502c60a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkBtnSave&quot;)</value>
      <webElementGuid>ac3370c9-0038-4af5-a5aa-6265a73174be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LinkBtnSave']</value>
      <webElementGuid>d50e5164-51f1-47ff-a261-39da5b680738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/section[2]/div/div[2]/div[3]/div[2]/a[2]</value>
      <webElementGuid>e7f969ff-31d6-42ee-af90-304bd6c1514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Kontrak/Plat Nomor'])[1]/following::a[2]</value>
      <webElementGuid>28732e56-f0e6-40c4-b43e-3d26c6232822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Agreement'])[1]/following::a[2]</value>
      <webElementGuid>08bb1d5a-9f84-440c-9c57-618297f19f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Kontrak'])[1]/preceding::a[1]</value>
      <webElementGuid>d58976d9-040d-4da0-a31a-adcf413a1622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ApplicationID'])[1]/preceding::a[1]</value>
      <webElementGuid>843da9a3-0e7f-4dfa-9f21-bee00f979798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('LinkBtnSave','')&quot;)]</value>
      <webElementGuid>69ae0a9c-35d3-49b0-8274-6569672269f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5cd37b57-cdf6-4d6e-ac1f-4141d296c0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LinkBtnSave' and @title = 'Save' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;LinkBtnSave&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>bd04c60a-bdfe-4f11-9699-444a92e56da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
