<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>86b02a81-b345-4db3-ba34-d4ff22a5240f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvDetail_checkbox_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvDetail_checkbox_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>548a8352-2a4a-420f-b3ce-e62052e17542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvDetail_checkbox_0</value>
      <webElementGuid>12ffafca-fa5e-46c6-b8f8-eee97c7f2aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>96327e5d-7c73-4797-92e8-eb836be2f7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvDetail$ctl02$checkbox</value>
      <webElementGuid>1426a17d-432b-474c-8ce1-ac2bd0035662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvDetail$ctl02$checkbox\',\'\')', 0)</value>
      <webElementGuid>126621c5-4668-4878-85da-9f7c93036473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvDetail_checkbox_0&quot;)</value>
      <webElementGuid>fda9afcd-a525-418d-8ee5-f4dcfe7f9b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvDetail_checkbox_0']</value>
      <webElementGuid>f27f7b53-dc33-448e-91b6-b681e5d99001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvDetail']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>92672cc6-b14f-44fc-be7a-fb894640b39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>9748e5e4-3041-466f-b3c0-373320c0459e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvDetail_checkbox_0' and @type = 'checkbox' and @name = 'gvDetail$ctl02$checkbox']</value>
      <webElementGuid>0e341f73-eb2b-4c84-bb23-37a8400ac2a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
