<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. KontrakPlat Nomor_txtvalue</name>
   <tag></tag>
   <elementGuidId>775ab09a-dfa6-4e51-b0b5-eb1e0e1285f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtvalue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtvalue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtvalue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17f7dde4-3768-4730-aa98-c2cf2c9b7710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtvalue</value>
      <webElementGuid>f82fcbe0-43ca-4b3f-98cd-3bd8640a0ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f81a914-5fa1-4c30-a817-d4cfeb89205a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5b2b2ddb-5477-4106-90f6-4e7e1387e57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtvalue</value>
      <webElementGuid>8b0d12d9-e5bb-496e-8eb9-aedb598af1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b784ad47-414e-4fd2-8f74-10bec7fc367d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtvalue&quot;)</value>
      <webElementGuid>0065bd17-d2ac-468c-ab3a-0648cab60952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtvalue']</value>
      <webElementGuid>5b2aba49-305c-4e14-ba99-84a4c314c057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/section[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>bee10f83-a064-465a-a877-df70bdded0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bc3d4d72-9619-4e8a-96d6-7475c7105767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtvalue' and @type = 'text' and @id = 'txtvalue']</value>
      <webElementGuid>bd18981b-1a5b-4b24-8328-1b9cbaba1639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
