<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input nomor kontrak</name>
   <tag></tag>
   <elementGuidId>25998716-599e-46d9-8aa1-80605230bfa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtvalue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtvalue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>893fd4ef-bdda-47f1-86e2-88b13552b3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtvalue</value>
      <webElementGuid>8ddf13e6-ff0d-43d3-ad04-bbca847c6169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>255dd44e-cb44-4ba6-bc88-0aedd32de620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1c467a9-125a-4ab5-ab13-82b530febf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtvalue</value>
      <webElementGuid>0e712d36-e0c4-41b6-aac1-a1d3bfbf22b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>efebbb70-e552-441c-a179-ec70f3cf71e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtvalue&quot;)</value>
      <webElementGuid>7d64a53f-d95b-4dd0-8eaf-f78f38418f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtvalue']</value>
      <webElementGuid>102b7d58-b376-4c39-a74a-7b4a1e484bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/section[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3a64cd5f-0eb0-41c2-bf90-1af5ec800e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0398ef6f-8207-4d3b-b611-f41638276c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtvalue' and @type = 'text' and @id = 'txtvalue']</value>
      <webElementGuid>0a12e74f-e497-4e0c-bc41-0692784fafae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
