<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>e68ae62a-bb8d-4f6c-a32d-5689d7a35441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_gvDetail_linkcancel_0&quot;)/i[@class=&quot;fas fa-window-close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbsave']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1f5c1ab4-1880-4d4a-bac1-d5a006efce42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>78daf785-3bf2-4b40-9cac-917653f24f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbsave&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>f9a18d12-1511-4627-9917-ec17af54d2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbsave']/i</value>
      <webElementGuid>980555e5-df8e-4852-b91b-0c00f385f6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/i</value>
      <webElementGuid>6691584a-6bc1-4b2f-952c-dd4cab55f867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
