<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Penyelesaian</name>
   <tag></tag>
   <elementGuidId>d822348e-2f61-40b9-af53-b1014f3a02b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>540f2339-b2b9-4ec8-809b-420e7f889032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>c48d4257-9568-4401-b992-346a6369c7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ComplaintSystem/MasterPenyelesaian.aspx</value>
      <webElementGuid>acdc6940-16ec-428c-887b-83925e441008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t4</value>
      <webElementGuid>bd9d6202-2446-4bcc-81af-2ffd1bce04b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Penyelesaian</value>
      <webElementGuid>eaaf2e11-d7fb-4a05-8e08-23ff2188f873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t4&quot;)</value>
      <webElementGuid>98a1ac09-40f3-4c8d-bd9c-9056faba9ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t4']</value>
      <webElementGuid>8761e1cd-bb37-410a-87cc-79029f30ea00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n0Nodes']/table[4]/tbody/tr/td[3]/a</value>
      <webElementGuid>ab2eecf3-37af-4ae9-96ee-dd30c257ab5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Penyelesaian')]</value>
      <webElementGuid>9fc1ac5b-48f3-41a1-9f98-5a2f94a6fc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Masalah'])[1]/following::a[1]</value>
      <webElementGuid>b75c1d54-1b51-41fd-a8f2-fb4591a2ffe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Sub Kategori'])[1]/following::a[2]</value>
      <webElementGuid>c563ec06-d5d7-4c95-8424-13c2d9725d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matriks Kategori'])[1]/preceding::a[1]</value>
      <webElementGuid>c6ad5ffa-c256-4fca-bad5-0a5448342e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master SLA'])[1]/preceding::a[2]</value>
      <webElementGuid>8228fb7c-4c8b-4efc-9d87-2239fd5b0155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Penyelesaian']/parent::*</value>
      <webElementGuid>393d266e-d479-46f7-b5f0-f1481bb1345e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ComplaintSystem/MasterPenyelesaian.aspx')]</value>
      <webElementGuid>60ee0bcc-e832-4521-a303-98e68e2f6cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td[3]/a</value>
      <webElementGuid>833eaa10-71a2-4fb1-9d45-d3683d065fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ComplaintSystem/MasterPenyelesaian.aspx' and @id = 'TreeView1t4' and (text() = 'Master Penyelesaian' or . = 'Master Penyelesaian')]</value>
      <webElementGuid>5d698f6e-9496-4e71-9338-69e3dc5d4ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
