<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input edit</name>
   <tag></tag>
   <elementGuidId>4958fec5-e6ef-4932-a1b6-e08f6a06c604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvDetail_txtpenyelesaian_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvDetail_txtpenyelesaian_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db535245-d715-495c-bab7-f05b50fce024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvDetail$ctl02$txtpenyelesaian</value>
      <webElementGuid>5d201610-7fdb-48f3-bbcf-5e140efb5101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d62fd03d-1999-4b6f-ba29-094c5739e34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Melakukan alokasi pelunasan normal Debitur</value>
      <webElementGuid>fea04b72-d9e9-49cc-8c2c-e5ed024697f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvDetail_txtpenyelesaian_0</value>
      <webElementGuid>345b64ea-f081-4d02-8481-be8f4fd06e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9fe1f6eb-92c2-4fb8-b55c-de502d391eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_txtpenyelesaian_0&quot;)</value>
      <webElementGuid>76e867aa-f7d4-439d-9453-403611d809da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvDetail_txtpenyelesaian_0']</value>
      <webElementGuid>a19b04b3-c94b-4f52-a99e-60f37d512b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvDetail']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>bd27aea4-5887-4b6f-bdb5-744292784176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>afb3f69b-5320-4535-8f2e-086105ca246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$gvDetail$ctl02$txtpenyelesaian' and @type = 'text' and @id = 'main_gvDetail_txtpenyelesaian_0']</value>
      <webElementGuid>02cfb78d-f6f2-477c-a691-47e9a7705398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
