<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus</name>
   <tag></tag>
   <elementGuidId>b7997ffb-0e16-4c01-8792-ae66420c2a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbadd']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-plus-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a45974c0-37e4-4468-951c-010b1e2dca70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-plus-square</value>
      <webElementGuid>798fc51f-907a-44f5-a94d-2b0e1059598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbadd&quot;)/i[@class=&quot;fas fa-plus-square&quot;]</value>
      <webElementGuid>65d7a536-e25c-4bcb-bd17-123821a44e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbadd']/i</value>
      <webElementGuid>fd3d20c2-cc9d-480c-a82e-93e3aa64fe2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>75ada78d-edab-4ec4-a15e-6263416fd861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
