<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No</name>
   <tag></tag>
   <elementGuidId>61b41763-979d-486c-a300-d8fa733b7395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_rbditangani_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'main_rbditangani_1' and @type = 'radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_rbditangani_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>971400ce-f19d-4b30-877c-ea40111c64bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_rbditangani_1</value>
      <webElementGuid>025386f5-f6d2-482b-a131-cf5208defc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a85fb1be-84aa-4e19-b8f5-b4b26fc48f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$rbditangani</value>
      <webElementGuid>e47badf0-f2c4-49cd-9792-9c056599dc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c64045c8-0922-48cb-8966-3992c3ecb612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_rbditangani_0&quot;)</value>
      <webElementGuid>d311396c-feca-4d94-86c3-70150a6a7012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_rbditangani_0']</value>
      <webElementGuid>a01dbe4b-d294-4623-9455-21c0b36db136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_rbditangani']/tbody/tr/td/input</value>
      <webElementGuid>9fa237ac-09b4-4a46-becd-bcb850d0c3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>b7eea123-76fc-49a9-ba9d-4bdf256cbc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_rbditangani_0' and @type = 'radio' and @name = 'ctl00$main$rbditangani']</value>
      <webElementGuid>51db6ce9-1f6d-4523-a433-39ae8a8b6a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
