<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yes</name>
   <tag></tag>
   <elementGuidId>da733d1f-6bc3-45fc-945b-130621130ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_rbditangani_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'main_rbditangani_0' and @type = 'radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_rbditangani_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6361c163-5626-4503-b9ab-aecc805b750b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_rbditangani_0</value>
      <webElementGuid>a065e645-00f3-489b-a85d-23fcf34f6a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>554a2cce-37c4-4db5-b4bb-5c059255305a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$rbditangani</value>
      <webElementGuid>95be2601-e5d4-4a6b-bb03-49e3ae5b5a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46e0e2d6-9cc3-4d7d-ae9d-4822cae20e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_rbditangani_0&quot;)</value>
      <webElementGuid>140a7005-62fc-4b57-a06a-697434e6fc19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_rbditangani_0']</value>
      <webElementGuid>eedb975e-7aba-4fb2-a1e7-b5f7b0c13fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_rbditangani']/tbody/tr/td/input</value>
      <webElementGuid>e874534e-1ef5-4c63-9535-e10ac3cc28f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>3ec2f0bb-b2e3-48b2-a3a0-35080b43442d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_rbditangani_0' and @type = 'radio' and @name = 'ctl00$main$rbditangani']</value>
      <webElementGuid>ae2c2af1-3680-4b49-9439-34f1fcb1d13a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
