<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon doc check</name>
   <tag></tag>
   <elementGuidId>75e49aa3-cf92-4db3-a787-b1824496c8f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_gvPenanganan_lbldoc_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvPenanganan_lbldoc_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e1ca2d3-dcc4-4a02-a7d8-9d1b06239da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>61e08610-0ae4-482f-a1f1-d332fb5c2918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvPenanganan$ctl02$lbldoc</value>
      <webElementGuid>accb3aa2-2178-4996-b2aa-84ad363308de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>04543692-b5aa-458b-ab89-32aa4492b106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvPenanganan_lbldoc_0</value>
      <webElementGuid>6f4bf00b-2064-48ca-a47a-fa70be9e3c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Document</value>
      <webElementGuid>bcc8d3c6-52e4-492b-9f8d-a71b8dfd8e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-sm fa</value>
      <webElementGuid>be64061b-5c69-41cf-be10-9e1104eea687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvPenanganan_lbldoc_0&quot;)</value>
      <webElementGuid>146e8f36-2fe7-45f4-9316-9b47fce6123d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvPenanganan_lbldoc_0']</value>
      <webElementGuid>4c0739e6-b6de-4acc-9d1b-484cab4068a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvPenanganan']/tbody/tr[2]/td[17]/div[2]/input[2]</value>
      <webElementGuid>7d613072-8f92-416c-ae7c-29fa36e34fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div[2]/input[2]</value>
      <webElementGuid>f6bcbff0-493a-442c-a465-c09a39341bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$main$gvPenanganan$ctl02$lbldoc' and @id = 'main_gvPenanganan_lbldoc_0' and @title = 'Document']</value>
      <webElementGuid>12de42fb-930e-4884-a636-170db084dac8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
