<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Keterangan Diatas Target SLA Waktu Tunggu</name>
   <tag></tag>
   <elementGuidId>4d08e9b1-1f84-4d38-9d3f-8c39b9961550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtketdiatastungu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtketdiatastungu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>943fa43e-72a2-49ff-afff-f726e35df25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtketdiatastungu</value>
      <webElementGuid>2510d433-5350-4b93-807b-c587ea586286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>853bf41b-982f-4a12-b0c8-8ef669ed38d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtketdiatastungu</value>
      <webElementGuid>0760a37d-4b5d-400e-980d-dd39d6df6065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f7df20c2-8ea2-4b3e-93c1-4578a8b1149a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtketdiatastungu&quot;)</value>
      <webElementGuid>de2744c8-250b-483e-b245-7d65aefc06d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtketdiatastungu']</value>
      <webElementGuid>efaadb14-26d6-4abb-be81-61c9d784aff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnldiatastunggu']/div/div/input</value>
      <webElementGuid>6401ec02-fa64-4f36-984c-3f7b8c8f3338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>3974f3b7-05c2-4393-bde1-ea7eb7d87bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtketdiatastungu' and @type = 'text' and @id = 'main_txtketdiatastungu']</value>
      <webElementGuid>93feab04-0afe-4d5a-a3f3-295b25188d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
