<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approve</name>
   <tag></tag>
   <elementGuidId>ddd67a20-20ef-4beb-aec8-e30c34b1ea51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'submit' and @id = 'main_gvPenanganan_lblApprove_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvPenanganan_lblApprove_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvPenanganan_lblApprove_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a536417-5981-4065-9045-428c3ede7b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>88ecd24b-7163-4d2a-b58a-50d3c1583e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvPenanganan$ctl02$lblApprove</value>
      <webElementGuid>d6f26a24-6e42-4206-b313-411943e6aa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>859e3a2c-2004-486c-a78e-809800829e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Approve Penanganan ? ');</value>
      <webElementGuid>f0079def-af04-4ee1-aac6-c06f93225010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvPenanganan_lblApprove_0</value>
      <webElementGuid>e22d53cb-829f-4d1a-8190-c5595c6a65da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>9f4abfa4-aa72-4549-84f6-a351857a946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm fa</value>
      <webElementGuid>a98ec05a-07f5-417f-83fe-cac1dfe14586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvPenanganan_lblApprove_0&quot;)</value>
      <webElementGuid>591e03fa-00e0-4c8a-b447-c7a754bbee64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvPenanganan_lblApprove_0']</value>
      <webElementGuid>4eb3617b-9fbe-4674-9b86-9583ea44760b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvPenanganan']/tbody/tr[2]/td[17]/div[2]/input</value>
      <webElementGuid>a4fc0897-d113-4f0a-9558-6afdf4fdae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div[2]/input</value>
      <webElementGuid>87d85aab-0e6a-4663-a8ea-532f578fe785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$main$gvPenanganan$ctl02$lblApprove' and @id = 'main_gvPenanganan_lblApprove_0' and @title = 'Approve']</value>
      <webElementGuid>6b3f3874-e436-4dec-851a-2530001e77d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
