<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP Debitur (jika ada perubahan)</name>
   <tag></tag>
   <elementGuidId>2154d232-5096-47a2-bfcd-2b689f69742c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtnohp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtnohp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65f2c12a-3a3a-4fec-99d0-c2ff5f48d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtnohp</value>
      <webElementGuid>6adabb2a-09b2-410e-9ee8-e24c62d945ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>188af3ca-8d79-415d-9e23-1012202b2d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtnohp</value>
      <webElementGuid>69d84740-52a8-4faf-a594-6a388f30a202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6368b4d7-7564-4c45-9836-575ecf779b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtnohp&quot;)</value>
      <webElementGuid>717177d4-dac6-4547-9f72-3446a8bfdd44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtnohp']</value>
      <webElementGuid>b2b3fc01-d59f-4e9f-b435-c18b2c06c5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnl7']/div[5]/div/input</value>
      <webElementGuid>a178f2a2-7163-4d18-919f-530b4fd091c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[5]/div/input</value>
      <webElementGuid>36d1f86e-b6e6-4029-a74c-094e9de2e30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtnohp' and @type = 'text' and @id = 'main_txtnohp']</value>
      <webElementGuid>219555a1-6c01-4645-949b-8d74052b9268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
