<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Emergency Kontak (jika ada perubahan)</name>
   <tag></tag>
   <elementGuidId>3043f3fe-e2a9-44a6-abeb-ee6cab4b3e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtnamaemergency2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtnamaemergency2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f747bffd-4e94-428e-bcbc-a578aeb7e4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtnamaemergency2</value>
      <webElementGuid>2c3379b9-06b8-4493-847f-e8433dcc0dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3339bd2e-8883-4fcd-ac87-bf05989043ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtnamaemergency2</value>
      <webElementGuid>5b6401b9-f0e3-4801-b03f-d7e97b13cba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86fb5d5a-222c-4597-a364-197ce1700358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtnamaemergency2&quot;)</value>
      <webElementGuid>fdf41ede-9d7f-4d6a-a40b-ecf88a76cd70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtnamaemergency2']</value>
      <webElementGuid>83677dea-f60a-4e2c-8db0-b11981e594d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnl1']/div[5]/div/input</value>
      <webElementGuid>812bcd5f-0c06-4828-b45b-d3d5df4dd0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[5]/div/input</value>
      <webElementGuid>594b144c-227e-41a3-a8ac-051564826a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtnamaemergency2' and @type = 'text' and @id = 'main_txtnamaemergency2']</value>
      <webElementGuid>7f37b776-3b84-4a21-9877-6dc4360c7647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
