<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Emergency Kontak Jika Ada Perubahan</name>
   <tag></tag>
   <elementGuidId>8956c12f-a490-4790-8844-25195450ecdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtnoemergency2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtnoemergency2&quot;)[count(. | //input[@id = 'main_txtnoemergency2']) = count(//input[@id = 'main_txtnoemergency2'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtnoemergency2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>750ba863-68a9-4de1-9951-acafcd1343c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtnoemergency2</value>
      <webElementGuid>57a6b9de-744d-4f8b-82d6-cc6a92fc1413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43c95e98-c15e-4b97-9689-d9af7e51487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtnoemergency2</value>
      <webElementGuid>80f5e1fc-c7d0-4695-a19d-bbc8b7a6e4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c5fca03-f32f-4eb2-833f-7afb83a248c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtnoemergency2&quot;)</value>
      <webElementGuid>174928e1-6e49-4da5-b335-e44e88079006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtnoemergency2']</value>
      <webElementGuid>0bbd27ab-1038-4563-bc26-1984165c0067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnl1']/div[6]/div/input</value>
      <webElementGuid>dd41aaf2-50a3-477b-b03c-e996164100c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[6]/div/input</value>
      <webElementGuid>410dd407-444c-4c66-95a3-7d0448c1725d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtnoemergency2' and @type = 'text' and @id = 'main_txtnoemergency2']</value>
      <webElementGuid>33bbe144-75b1-4068-ad0b-088cf8bfbf74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
