<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pengunjung</name>
   <tag></tag>
   <elementGuidId>6fe810ab-7811-4c89-859a-d24d3c90b4e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtpengunjung']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtpengunjung</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90706a89-9111-42bb-8358-a7d626cc482b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtpengunjung</value>
      <webElementGuid>546439e9-bab7-46ab-8653-b5e395570458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c61f5aef-4263-4eb8-8a8f-04f574ff5386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtpengunjung</value>
      <webElementGuid>030a6356-d1d3-4c79-82d2-74d7b14c53c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24189d2e-50b0-4ff7-afe9-0099753e2917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtpengunjung&quot;)</value>
      <webElementGuid>79092c98-7d24-41ab-9bdf-45170ed3ba51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtpengunjung']</value>
      <webElementGuid>88b621cf-b60f-463b-ae5e-3eaed51fb53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div/div/div[6]/div/input</value>
      <webElementGuid>73fadc30-ef09-478c-888d-b2ad13e2f407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>28859abd-5ee7-43fe-a4a4-9356aa4d3874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtpengunjung' and @type = 'text' and @id = 'main_txtpengunjung']</value>
      <webElementGuid>9f907f79-9b02-48e0-831d-3671a495f15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
