<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Debitur (jika ada perubahan)</name>
   <tag></tag>
   <elementGuidId>77233046-c74b-4226-aded-52bf6590df88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtemail2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtemail2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd502c21-ca5a-4f18-a4c3-10644c7e0bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtemail2</value>
      <webElementGuid>5e959661-aa7c-4fb1-9c27-1dc8865a89e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0608da6-30f6-4ac2-86df-e2c09c6adbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtemail2</value>
      <webElementGuid>5a15e414-0712-45be-8be8-9b208397adf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e244c1a6-d1c7-44fe-86f7-89a15db3697a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtemail2&quot;)</value>
      <webElementGuid>ea6dd68a-b01a-483a-a547-d1cefdc5f01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtemail2']</value>
      <webElementGuid>a488bca3-206f-4d69-8520-4f8144eba90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnl1']/div[2]/div/input</value>
      <webElementGuid>606633da-abc3-41dc-a875-a5143f728d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>58968f80-bc98-4fb6-a6d4-e58e8542fd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtemail2' and @type = 'text' and @id = 'main_txtemail2']</value>
      <webElementGuid>f883dcae-672e-49f5-9e81-f083a80ef8d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
