<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Domisili Debitur (jika ada perubahan)</name>
   <tag></tag>
   <elementGuidId>2957104b-fbc7-4519-8d89-e769e23261c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtalamatdomisili2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtalamatdomisili2&quot;)[count(. | //input[@type = 'text' and @id = 'main_txtalamatdomisili2']) = count(//input[@type = 'text' and @id = 'main_txtalamatdomisili2'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtalamatdomisili2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372a3e69-dd58-4fea-9d40-19f3a1151dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtalamatdomisili2</value>
      <webElementGuid>56c87c1b-564d-4aba-ac19-501e0e638498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e463f28-a9c2-431b-97a3-0504e5ba5e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtalamatdomisili2</value>
      <webElementGuid>4aaa0f5c-3feb-4ed2-8928-06fe74df8a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>40b1416e-28ff-4ffa-aeb8-f9ba483a36d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtalamatdomisili2&quot;)</value>
      <webElementGuid>d21e4728-5dbd-4b73-83cb-45fd07063560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtalamatdomisili2']</value>
      <webElementGuid>c3e216f1-1e8c-4739-8679-b3fd43e178b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnl7']/div[3]/div/input</value>
      <webElementGuid>616dd273-cbb5-4201-950d-71ad41ff861c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/input</value>
      <webElementGuid>7837d8fd-cb3f-4602-bc68-1bd4fe309918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtalamatdomisili2' and @type = 'text' and @id = 'main_txtalamatdomisili2']</value>
      <webElementGuid>f12e273f-807e-49a8-a112-bef674c81071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
