<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Sub Kategori</name>
   <tag></tag>
   <elementGuidId>17e02d76-754f-4fc7-8400-896abd9c79e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84605fde-b947-4098-bfee-4f4f26334388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>896e1e93-aa6c-42eb-bc3a-a6a360bbc821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ComplaintSystem/MasterSubKategori.aspx</value>
      <webElementGuid>c9f275c8-e59e-4bb6-9c37-2cc947fa3026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t2</value>
      <webElementGuid>4a2a822c-c330-478c-9b82-58d9bb1f3b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Sub Kategori</value>
      <webElementGuid>d6ba462a-1623-45b0-82f1-ddaa833c6df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t2&quot;)</value>
      <webElementGuid>fac5e649-d0c2-4b59-aa42-004697f36755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t2']</value>
      <webElementGuid>3558a4ad-4c0f-42bb-a022-1a216c4219bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n0Nodes']/table[2]/tbody/tr/td[3]/a</value>
      <webElementGuid>86409546-7a02-49c5-9740-b1348b425ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Sub Kategori')]</value>
      <webElementGuid>d2240c36-6ae3-4141-817a-50b746449ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Kategori'])[1]/following::a[1]</value>
      <webElementGuid>e2a60f23-fa4f-4d14-882d-9645d498517b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::a[2]</value>
      <webElementGuid>cab51b53-17a0-45b7-88d2-f2340cb01078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Masalah'])[1]/preceding::a[1]</value>
      <webElementGuid>59cf47eb-15d4-4eba-95d4-083f3acfce22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Penyelesaian'])[1]/preceding::a[2]</value>
      <webElementGuid>0fc391d4-b059-4ca9-8be7-77193e3b56df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Sub Kategori']/parent::*</value>
      <webElementGuid>efaa3bde-63b5-4f0c-a7e6-bed19331b082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ComplaintSystem/MasterSubKategori.aspx')]</value>
      <webElementGuid>6f397eda-98e8-435a-a058-f09bb953430c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[3]/a</value>
      <webElementGuid>947cdaa7-1677-47ac-b9df-635328285795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ComplaintSystem/MasterSubKategori.aspx' and @id = 'TreeView1t2' and (text() = 'Master Sub Kategori' or . = 'Master Sub Kategori')]</value>
      <webElementGuid>3fadf23b-8294-4c67-8724-2826fc8dd32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
