<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check</name>
   <tag></tag>
   <elementGuidId>3d4536fa-76b9-48f2-9184-e59f4530957c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_gvDetail_linkUpdate_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e9b1c2a8-1116-4023-9587-afc5f14c7a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-check</value>
      <webElementGuid>24ac5083-1bd6-4d6b-980a-761e0743403d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_linkUpdate_0&quot;)/i[@class=&quot;fas fa-check&quot;]</value>
      <webElementGuid>73de88a9-b08c-4875-a920-18507d8de38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_gvDetail_linkUpdate_0']/i</value>
      <webElementGuid>0f0f4f9a-df42-40ce-839d-9d69118ad167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a/i</value>
      <webElementGuid>4eed501b-e961-4b7f-ac92-39ede6176335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
