<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close</name>
   <tag></tag>
   <elementGuidId>dcedae52-e6d7-434e-a9b3-6c06ca5ed757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_gvDetail_linkcancel_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-window-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>acee5afa-ef16-4583-824c-14ae9f2eb488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-window-close</value>
      <webElementGuid>4b3d7305-e92b-4d70-bfae-4a0b7fad3618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_linkcancel_0&quot;)/i[@class=&quot;fas fa-window-close&quot;]</value>
      <webElementGuid>bfe155aa-9d4c-4745-b511-f7d901958fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_gvDetail_linkcancel_0']/i</value>
      <webElementGuid>f429c09e-d730-4d99-a204-f669b12e7523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a[2]/i</value>
      <webElementGuid>01bf8430-d7aa-43d8-ac27-fed2b339f494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
