<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input edit subkategori</name>
   <tag></tag>
   <elementGuidId>3643c83d-7f87-4dff-9628-16dcc6c0d38f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvDetail_txtsubkategori_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvDetail_txtsubkategori_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4816c47-da00-4c16-b0e4-8be23bcbf6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvDetail$ctl02$txtsubkategori</value>
      <webElementGuid>c9f16e37-969a-4198-b7e8-cdcd1fa999d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4333e00c-6f84-4549-8c2c-9fb840995914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prosedur alih kontrak</value>
      <webElementGuid>1c1ee934-1ff3-44b6-9ead-023360d047c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvDetail_txtsubkategori_0</value>
      <webElementGuid>b208e1a8-10f5-42b9-a848-300ba3906bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a781e0a2-b3a9-414f-8160-b380349cca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_txtsubkategori_0&quot;)</value>
      <webElementGuid>3b17c6fd-78a9-487c-8326-b82a17609aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvDetail_txtsubkategori_0']</value>
      <webElementGuid>9628093c-846a-4b72-b776-5ef089a0f3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvDetail']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>3bebe79c-6bb6-4974-9abe-567894c08e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>46a9a9b9-f846-4e25-8422-dc868b084a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$gvDetail$ctl02$txtsubkategori' and @type = 'text' and @id = 'main_gvDetail_txtsubkategori_0']</value>
      <webElementGuid>9af0f641-3632-4dce-97a4-2071448a0f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
