<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sub Kategori</name>
   <tag></tag>
   <elementGuidId>8cdf9230-a596-444d-a4ff-0a007eeaab78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtsubkategoridesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtsubkategoridesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b568dff9-9f7a-45e9-879c-4c304afd5a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtsubkategoridesc</value>
      <webElementGuid>6ccc2bb6-1799-4bfe-a92d-fa1b67829997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>03d40aad-fb4f-484b-92f4-7a0fa45908c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>75b6dcdc-efdc-46d6-9c7f-e8eb44405073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtsubkategoridesc</value>
      <webElementGuid>51313b7b-0162-4af3-ba14-fc28772e9c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtsubkategoridesc&quot;)</value>
      <webElementGuid>bd494ce0-451b-4ece-b554-eec4829522bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtsubkategoridesc']</value>
      <webElementGuid>a6c75b17-6e46-47f0-a543-246489b5c3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div/div/textarea</value>
      <webElementGuid>1811723f-c39b-493b-9ce7-ba4271d4f6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3d79255a-f79f-4d52-900f-69fd6246c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtsubkategoridesc' and @id = 'main_txtsubkategoridesc']</value>
      <webElementGuid>e1b6009d-1ffe-4dca-9407-3cdda90404ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
