<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SLA Min</name>
   <tag></tag>
   <elementGuidId>8efb8ced-17b7-4ff8-b307-61d69f3d9dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtslamin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtslamin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0fcf47a-78a6-4546-aa2c-681efb8a0889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtslamin</value>
      <webElementGuid>fb399427-9159-431b-888e-21d304c517a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c77f7395-21b1-4a3b-a297-37af17b91f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e88f33d2-67d8-4264-99c2-885514da590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtslamin</value>
      <webElementGuid>6ef50ed5-485b-40e9-98f5-1a405844b051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cd0d61e-6445-4f10-86df-4332716d18c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isnumerickey(event);</value>
      <webElementGuid>50d9f584-d9bf-477f-bad8-07dde65cc18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtslamin&quot;)</value>
      <webElementGuid>17395d31-93d8-4b3d-9651-fafd4d7be0f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtslamin']</value>
      <webElementGuid>a7e7a623-2a45-45e4-8504-11646e97dd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_pnlSLAMinMax']/div/div/input</value>
      <webElementGuid>1438e41a-0ee1-4509-b066-610d0c9be2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>514e6e5f-fe40-4a09-b823-8799f48f25ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtslamin' and @type = 'text' and @id = 'main_txtslamin']</value>
      <webElementGuid>b2e0a157-4f85-445d-acdf-d301cc29f93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
