<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No</name>
   <tag></tag>
   <elementGuidId>5862f2ab-9c7e-43f6-ad53-c4cd6ccba331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_rbnohp_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'main_rbnohp_1' and @type = 'radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_rbnohp_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb5fdb8c-e74d-4349-a4d8-3991eca734c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_rbnohp_1</value>
      <webElementGuid>1b74c5c8-cfc5-437f-a952-2419f2ef7ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c0eb90f3-558b-4308-9402-d8c0ba2b7718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$rbnohp</value>
      <webElementGuid>fce4044f-9741-4e7d-bf26-986021cef593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>794b634d-f9f6-4317-ad40-2ae53e3c14bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_rbnohp_0&quot;)</value>
      <webElementGuid>3a2fd580-eb4f-4283-a417-16c632cd1b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_rbnohp_0']</value>
      <webElementGuid>5e3a8ba1-823e-4d96-9a54-7f76d1049fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_rbnohp']/tbody/tr/td/input</value>
      <webElementGuid>5f6d0a6a-4a64-4463-85c0-944fd9175269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a7381801-71ac-44d1-b4e1-89a0bdd92329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_rbnohp_0' and @type = 'radio' and @name = 'ctl00$main$rbnohp']</value>
      <webElementGuid>896ec1cf-f192-4ba3-8329-39fde243fe78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
