<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yes</name>
   <tag></tag>
   <elementGuidId>e7a80c9c-0992-464a-a9cb-c18033cc7ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_rbnohp_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'main_rbnohp_0' and @type = 'radio' and @name = 'ctl00$main$rbnohp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_rbnohp_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c59c09fb-e2db-416d-8604-43e8f5f5f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_rbnohp_0</value>
      <webElementGuid>69ffc713-5fb2-43ed-a6f2-1eec099ce3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>de18f050-642e-4774-add0-47307080ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$rbnohp</value>
      <webElementGuid>c0ba7b91-a490-415d-8368-aebda9ae8ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9a017b8-9376-4cb5-97b9-7f91b01c522e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_rbnohp_0&quot;)</value>
      <webElementGuid>0efb6c30-52f5-483a-8c8b-4e0604bce06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_rbnohp_0']</value>
      <webElementGuid>594cec7d-6f8b-4935-8ea3-287aedeb0ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_rbnohp']/tbody/tr/td/input</value>
      <webElementGuid>bc382f3b-6088-4695-a01d-05f6fb1c89bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>197c3a4e-e532-475d-940b-e2ee038445e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_rbnohp_0' and @type = 'radio' and @name = 'ctl00$main$rbnohp']</value>
      <webElementGuid>ae238b88-fc27-426b-a92a-2cc874aca0be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
