<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close</name>
   <tag></tag>
   <elementGuidId>f343a9b1-02c8-487d-a5bc-655ea7c8d893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_gvDetail_linkcancel_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-window-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c40cf159-4ece-426c-99aa-c8706fd430e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-window-close</value>
      <webElementGuid>d570ce43-9ef5-484e-982f-c3ebb22d5a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_linkcancel_0&quot;)/i[@class=&quot;fas fa-window-close&quot;]</value>
      <webElementGuid>40d11bfd-60a3-44f6-aae8-50a61fcb47a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_gvDetail_linkcancel_0']/i</value>
      <webElementGuid>a8708981-12c5-4b35-aa0a-9f1a374cf0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a[2]/i</value>
      <webElementGuid>4b1ceec4-c3f4-4a06-99d0-b3d9815a0e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
