<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>60ce58bc-5f2f-444e-86f8-7a907c264b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_gvDetail_linkEdit_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc112be0-331c-420f-bf4d-71b8036a906f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-edit</value>
      <webElementGuid>ad83a556-04c8-4b44-bf17-81dd9cb689b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_linkEdit_0&quot;)/i[@class=&quot;fas fa-edit&quot;]</value>
      <webElementGuid>f929cd34-9c1b-44ec-b7f5-b658802f86af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_gvDetail_linkEdit_0']/i</value>
      <webElementGuid>137b6d4a-a804-4880-97a7-82af4abf364b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a/i</value>
      <webElementGuid>963570ab-cfc9-4971-9e20-78d38c2d42c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
