<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input edit kategori</name>
   <tag></tag>
   <elementGuidId>a51c946b-d6fe-4c87-b695-2e7050dc9e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvDetail_txtkategori_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvDetail_txtkategori_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aef6658b-94c2-4f31-b55b-fe7aedda6bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvDetail$ctl02$txtkategori</value>
      <webElementGuid>c6b67c0e-ddd5-447c-980d-319b954f622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed28d5dc-a9a8-4c17-8fd9-0e7e51d68e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Alih kontrak</value>
      <webElementGuid>bd22c8f3-96ab-4ac6-83e8-21fdcf4119d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvDetail_txtkategori_0</value>
      <webElementGuid>6ed44c77-ee63-47c4-8749-4737b7d8f7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cfec90b9-6dd4-4132-8a60-6292d429409d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_txtkategori_0&quot;)</value>
      <webElementGuid>c51c9fcb-fbc6-4205-afba-37272343a4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvDetail_txtkategori_0']</value>
      <webElementGuid>865c845f-4da5-464f-b2a0-59ec56cf1e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvDetail']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>08e25a3c-54e0-4043-be23-524400869eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>049d5233-5151-4ded-858c-242de0d0d39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$gvDetail$ctl02$txtkategori' and @type = 'text' and @id = 'main_gvDetail_txtkategori_0']</value>
      <webElementGuid>cea81b32-0900-47bd-8565-5346c41ab899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
