<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Pertanyaan</name>
   <tag></tag>
   <elementGuidId>838c0027-4123-406f-8857-c319572e9144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1730a61e-a21d-4b1f-a19f-36183cd18a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>7bf6abf6-d29b-4e74-af93-676892d7f04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ComplaintSystem/MasterPertanyaan.aspx</value>
      <webElementGuid>b372ef88-0b40-4931-9a5f-ab883d374b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t7</value>
      <webElementGuid>4823ee7e-54fb-4742-8faf-9b3910f3d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Pertanyaan</value>
      <webElementGuid>072e551f-c57b-48fd-b9d8-6752f87cbd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t7&quot;)</value>
      <webElementGuid>9b40caaa-7b26-4077-adbb-26c0633fd54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t7']</value>
      <webElementGuid>0f971146-e286-4e1a-910d-0dc38d85df20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n0Nodes']/table[7]/tbody/tr/td[3]/a</value>
      <webElementGuid>21149c8b-9c37-4ab9-ba9c-0cc057d94a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Pertanyaan')]</value>
      <webElementGuid>67125a3b-d848-4300-bd98-91499b120876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master SLA'])[1]/following::a[1]</value>
      <webElementGuid>bc59517b-2d62-4048-b74f-a246d4cc49fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matriks Kategori'])[1]/following::a[2]</value>
      <webElementGuid>edab8f34-2960-423a-a68a-5f896732b2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Antrian'])[1]/preceding::a[1]</value>
      <webElementGuid>70aa24ab-0dce-40c8-a417-f92b8be73580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Penanganan'])[1]/preceding::a[2]</value>
      <webElementGuid>7359b89d-954a-4f6b-b06a-5b59796f1856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Pertanyaan']/parent::*</value>
      <webElementGuid>c98c4b04-14be-40f4-8eef-5d24d549bdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ComplaintSystem/MasterPertanyaan.aspx')]</value>
      <webElementGuid>84aaea81-7d05-47c9-bd89-adcb91bd7cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[7]/tbody/tr/td[3]/a</value>
      <webElementGuid>14dfbca3-b901-4c37-9e8e-0a40b4255595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ComplaintSystem/MasterPertanyaan.aspx' and @id = 'TreeView1t7' and (text() = 'Master Pertanyaan' or . = 'Master Pertanyaan')]</value>
      <webElementGuid>eb6e04f2-5f2b-422f-8ffc-3859d8a72dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
