<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>f4f67353-8790-4144-b29b-7329ed2d31fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbsave']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1cc414d8-25d7-4901-b1c5-edf1763438a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>d95a030d-f8b4-439e-9889-b66ab2f68339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbsave&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>76ef2e16-a7fd-4536-a72b-86f15fa16230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbsave']/i</value>
      <webElementGuid>a2eb63ad-42d7-420e-8e7a-8d9344b44b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/i</value>
      <webElementGuid>ebfe4960-fabd-4307-8487-f67df2b3404c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
