<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea Pertanyaan</name>
   <tag></tag>
   <elementGuidId>cdb6b6d7-626e-4cd8-920b-add23e19f439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txtpertanyaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtpertanyaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>052b4065-37a0-44c1-b9ba-652eb59eb320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtpertanyaan</value>
      <webElementGuid>da3fce47-0bc5-4fd8-8507-3ff410f50f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e2d18010-92f5-499f-8a42-9a87f1f2a465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>2c8f8a8b-3e01-41cf-a529-975fa4efe260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtpertanyaan</value>
      <webElementGuid>c09f94c3-cd3e-48ea-bc88-4cbd36a183c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtpertanyaan&quot;)</value>
      <webElementGuid>011bfdf4-083b-4076-a4f1-56c38e56c04f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtpertanyaan']</value>
      <webElementGuid>b7425e46-bc1f-4278-9690-041333ae9508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div/div/textarea</value>
      <webElementGuid>466fe219-ecd3-42a8-973e-f4e3c28778d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>63fdbd2d-33e3-4c20-b986-9f5dd0df18ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtpertanyaan' and @id = 'main_txtpertanyaan']</value>
      <webElementGuid>8864fa50-ccda-4c75-8a69-31e5e7aa5ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
