<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Masalah</name>
   <tag></tag>
   <elementGuidId>42e87649-961c-44c9-bf7a-3137cfc22ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23cf25e0-87f8-49df-abe0-213bdf533b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>b0654cf4-5ddb-4fee-8014-a7368d2dd88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ComplaintSystem/MasterMasalah.aspx</value>
      <webElementGuid>aa1709c7-ac36-4120-9ec1-83f693ad2504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t3</value>
      <webElementGuid>fe85af2a-b55a-48c3-8265-8a7b43dff149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Masalah</value>
      <webElementGuid>fb035e1f-cc61-4daf-81f2-dfabf437528d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t3&quot;)</value>
      <webElementGuid>d74a2ab6-1274-48d4-89a5-a868aa1d4261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t3']</value>
      <webElementGuid>495245d8-e034-4bf5-a81c-210b2e7becec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n0Nodes']/table[3]/tbody/tr/td[3]/a</value>
      <webElementGuid>9b20b742-5e90-4b7f-9fdc-155dece82a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Masalah')]</value>
      <webElementGuid>ec4d684d-4dc9-46f3-a4a7-8fc288c9aaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Sub Kategori'])[1]/following::a[1]</value>
      <webElementGuid>88396e01-37c3-40b4-8c6d-cf2fcd6992b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Kategori'])[1]/following::a[2]</value>
      <webElementGuid>885547f3-7683-4ff0-b070-f93cceb5b170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Penyelesaian'])[1]/preceding::a[1]</value>
      <webElementGuid>31b7cfa8-f901-4ccb-818f-82a1e7d5aba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matriks Kategori'])[1]/preceding::a[2]</value>
      <webElementGuid>4382182d-b076-470f-8d96-ff2138d12c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Masalah']/parent::*</value>
      <webElementGuid>90279792-042b-42ef-8ba2-3679b844f7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ComplaintSystem/MasterMasalah.aspx')]</value>
      <webElementGuid>2542bbbc-9972-499c-a1cd-b3ccec7ed42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[3]/a</value>
      <webElementGuid>f6163530-7486-4259-8c96-9bf3bf0f9d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ComplaintSystem/MasterMasalah.aspx' and @id = 'TreeView1t3' and (text() = 'Master Masalah' or . = 'Master Masalah')]</value>
      <webElementGuid>1effd118-417c-4683-bcb6-3411884bcea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
