<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>c21acf0c-8053-4b67-a3f8-7f07ca40e44f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_gvDetail_linkEdit_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4db0254-b51d-4845-83d3-f54660ba9c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-edit</value>
      <webElementGuid>9bb5948c-97f0-4043-8749-b54f9806c87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_linkEdit_0&quot;)/i[@class=&quot;fas fa-edit&quot;]</value>
      <webElementGuid>0e9cf57a-e043-478c-a8c5-9d718c4d72ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_gvDetail_linkEdit_0']/i</value>
      <webElementGuid>305c998a-3c02-4d4b-ae3b-5acfca6fdaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a/i</value>
      <webElementGuid>a43e3f27-e980-45b4-b7a4-f8df964924cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
