<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input edit</name>
   <tag></tag>
   <elementGuidId>8ae6d530-08ca-41ad-b8d1-a80ee6805595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvDetail_txtmasalah_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvDetail_txtmasalah_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b1b2e4d-a038-4ec0-873d-6ba3b6d8c641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvDetail$ctl02$txtmasalah</value>
      <webElementGuid>ee576535-0777-4185-9ada-690392f5c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfc87b8f-6a94-4f43-82e9-79e45022fa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ahli waris Debitur mengeluhkan pencairan klaim asuransi yang telah diajukan.</value>
      <webElementGuid>ffa3de6b-144b-44d2-8d9f-708e3cb8d9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvDetail_txtmasalah_0</value>
      <webElementGuid>a12ec0b0-4613-4f53-bff6-fedc946b6527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>30a42d3d-2ea1-45ba-9cb9-9966d0ed8b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvDetail_txtmasalah_0&quot;)</value>
      <webElementGuid>9c02fce2-a39f-4264-b5aa-e48618fbf639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvDetail_txtmasalah_0']</value>
      <webElementGuid>2e5aa64f-b367-45d7-8eb0-dd7f46f1732f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvDetail']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>0da92f76-d63c-4e0a-b6f3-2d1211cec422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7c519c80-8982-49af-9eac-60537dcc330c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$gvDetail$ctl02$txtmasalah' and @type = 'text' and @id = 'main_gvDetail_txtmasalah_0']</value>
      <webElementGuid>184b6815-d1f5-43fa-b1e1-b8b3b6a5f580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
