<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view</name>
   <tag></tag>
   <elementGuidId>ac5c4277-3ae5-4c94-922d-e3bd85be48dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_gvPenanganan_lblview_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvPenanganan_lblview_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>525006e9-1d74-44e0-b4e1-4b2b8a06eca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>329f56da-f713-498c-95f1-7360b1066742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvPenanganan$ctl02$lblview</value>
      <webElementGuid>e5115926-0c59-458b-b17a-05beb251bdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2fbb156b-d568-4adc-97af-fece73fcf527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvPenanganan_lblview_0</value>
      <webElementGuid>6ca5d84d-2353-4bdb-8cce-582bacd1ab44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>ff712750-68fb-4018-8454-3ba7bedeca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm fa</value>
      <webElementGuid>28570a8c-ecb7-4c56-8214-1b8bb89f97f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvPenanganan_lblview_0&quot;)</value>
      <webElementGuid>6d8d2bf8-aed1-41af-8a70-463a4de7d329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvPenanganan_lblview_0']</value>
      <webElementGuid>d76fb7c3-2c8b-4bee-ba88-07e83087e5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvPenanganan']/tbody/tr[2]/td[17]/div/input</value>
      <webElementGuid>c7ec4ae3-e1bc-498a-b1cd-ab5493154c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div/input</value>
      <webElementGuid>00b0333a-90a2-4f9e-bf2a-ced0a644b17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$main$gvPenanganan$ctl02$lblview' and @id = 'main_gvPenanganan_lblview_0' and @title = 'View']</value>
      <webElementGuid>41a63e62-6008-4f5d-a164-b8371aae661e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
