<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Penanganan (1)</name>
   <tag></tag>
   <elementGuidId>b28ac0f1-d8bc-4ed8-99d3-c0f1669d08e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'Apps/ComplaintSystem/DaftarPenanganan.aspx' and @id = 'TreeView1t1' and (text() = 'Daftar Penanganan' or . = 'Daftar Penanganan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5813777c-893f-4012-891f-60115365b7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>f3f4a369-d932-426f-89ba-70e5475c342f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ComplaintSystem/DaftarPenanganan.aspx</value>
      <webElementGuid>62142ce4-e970-4649-b564-28075fbc7262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t1</value>
      <webElementGuid>fff1a670-052d-49bd-8b5c-6028ab9793bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Penanganan</value>
      <webElementGuid>ecdaa9aa-35db-4933-b0f6-d31f6773bb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t1&quot;)</value>
      <webElementGuid>bbaeb488-3429-401e-bf12-3899d10ef4f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t1']</value>
      <webElementGuid>1686d333-ef06-464b-86e0-3e2ccbf50f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>4a029d95-cc39-4dd2-a8e8-fa426b1211f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Penanganan')]</value>
      <webElementGuid>27ad5e15-9009-44eb-acc2-f5115b81008c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Antrian'])[1]/following::a[1]</value>
      <webElementGuid>d6429376-703e-4949-a977-805674fb12b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links.'])[1]/following::a[2]</value>
      <webElementGuid>802c1efd-2ded-4504-8b6f-3fadcb98fa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval List'])[1]/preceding::a[2]</value>
      <webElementGuid>b8af223c-261c-490a-8ef8-342277fef30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp Information'])[1]/preceding::a[2]</value>
      <webElementGuid>2c83d186-d215-464e-8331-410eb8474a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Penanganan']/parent::*</value>
      <webElementGuid>1b4c778e-aca6-4d12-ba0a-ba14f30d8ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ComplaintSystem/DaftarPenanganan.aspx')]</value>
      <webElementGuid>e44e6407-67a9-454b-b382-7a58ea7a8507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>01b9e19a-6e03-4efc-a658-3adfbfb3606d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ComplaintSystem/DaftarPenanganan.aspx' and @id = 'TreeView1t1' and (text() = 'Daftar Penanganan' or . = 'Daftar Penanganan')]</value>
      <webElementGuid>b8e2b636-4b69-4665-a741-7bfeda61cfc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
