<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>penanganan eskalasi</name>
   <tag></tag>
   <elementGuidId>37016701-c4af-4e7d-9023-8f6268f4325b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'submit' and @name = 'ctl00$main$gvPenanganan$ctl02$lbledit' and @id = 'main_gvPenanganan_lbledit_0' and @title = 'Eskalasi']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvPenanganan_lbledit_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvPenanganan_lbledit_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35a7d97c-46fe-4d95-aecc-415fc04e1bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d4a78b30-5da6-427c-8e4b-57579ff8230e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvPenanganan$ctl02$lbledit</value>
      <webElementGuid>09a14375-3b3e-445c-9b87-5ca354b5604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8dbfd71a-ed06-4c92-bb2f-edabaa5ecd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvPenanganan_lbledit_0</value>
      <webElementGuid>40b351c7-0613-4731-8eb3-3e7cde20b264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Eskalasi</value>
      <webElementGuid>5c285df4-b0f4-4b0d-90b7-dbefef14fbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-sm fa</value>
      <webElementGuid>67a1592e-29ff-4e47-81f2-20dab29f0764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvPenanganan_lbledit_0&quot;)</value>
      <webElementGuid>fe0faeef-0494-45b1-9322-2f274756aadf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvPenanganan_lbledit_0']</value>
      <webElementGuid>2ffe53ab-8776-4d7e-854c-6061d2a0540f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvPenanganan']/tbody/tr[2]/td[17]/div/input[2]</value>
      <webElementGuid>96438b73-8717-43f8-bab7-5f55b02ba0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div/input[2]</value>
      <webElementGuid>593af65f-a032-47da-bab3-1bc5fc5ca3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$main$gvPenanganan$ctl02$lbledit' and @id = 'main_gvPenanganan_lbledit_0' and @title = 'Eskalasi']</value>
      <webElementGuid>8ca3459a-6e32-476e-bde2-52e591ae18f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
