<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtnotiket-Search</name>
   <tag></tag>
   <elementGuidId>1c9efc86-53a9-4aa0-9b95-53020d74c630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txtnotiket</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtnotiket']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7b50a79-deb8-4e7a-8a22-a32be94ea47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtnotiket</value>
      <webElementGuid>25863ee3-29ac-4815-b9c0-f69864cb29e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efad6cae-23ff-441a-a404-f3ee652ebc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtnotiket</value>
      <webElementGuid>6c78c23b-5540-480d-b846-92c081cff917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>17743a6a-5902-4bb0-9a58-50c08990a50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtnotiket&quot;)</value>
      <webElementGuid>074dd63a-ea29-445e-bd53-2a330ed26c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtnotiket']</value>
      <webElementGuid>88d1ac7d-bd38-4226-919a-8fe06d7719aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div/div[2]/div[4]/div/input</value>
      <webElementGuid>37d2f9d1-3e2e-4559-8db6-6ba2285e4b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>7d0e2e43-9bc5-431f-8ac0-19c87eb34c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtnotiket' and @type = 'text' and @id = 'main_txtnotiket']</value>
      <webElementGuid>8b18cf95-ed91-406c-a1f3-5ae18b4d7384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
